/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRequiredRouteImport } from './routes/setup-required'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppScrapbookRouteImport } from './routes/_app/scrapbook'
import { Route as AppFinancesRouteImport } from './routes/_app/finances'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppBrandDealsRouteImport } from './routes/_app/brand-deals'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'

const SetupRequiredRoute = SetupRequiredRouteImport.update({
  id: '/setup-required',
  path: '/setup-required',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScrapbookRoute = AppScrapbookRouteImport.update({
  id: '/scrapbook',
  path: '/scrapbook',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancesRoute = AppFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandDealsRoute = AppBrandDealsRouteImport.update({
  id: '/brand-deals',
  path: '/brand-deals',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/setup-required': typeof SetupRequiredRoute
  '/analytics': typeof AppAnalyticsRoute
  '/brand-deals': typeof AppBrandDealsRoute
  '/dashboard': typeof AppDashboardRoute
  '/finances': typeof AppFinancesRoute
  '/scrapbook': typeof AppScrapbookRoute
  '/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/setup-required': typeof SetupRequiredRoute
  '/analytics': typeof AppAnalyticsRoute
  '/brand-deals': typeof AppBrandDealsRoute
  '/dashboard': typeof AppDashboardRoute
  '/finances': typeof AppFinancesRoute
  '/scrapbook': typeof AppScrapbookRoute
  '/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/setup-required': typeof SetupRequiredRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/brand-deals': typeof AppBrandDealsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/finances': typeof AppFinancesRoute
  '/_app/scrapbook': typeof AppScrapbookRoute
  '/_app/settings': typeof AppSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/setup-required'
    | '/analytics'
    | '/brand-deals'
    | '/dashboard'
    | '/finances'
    | '/scrapbook'
    | '/settings'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/setup-required'
    | '/analytics'
    | '/brand-deals'
    | '/dashboard'
    | '/finances'
    | '/scrapbook'
    | '/settings'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/setup-required'
    | '/_app/analytics'
    | '/_app/brand-deals'
    | '/_app/dashboard'
    | '/_app/finances'
    | '/_app/scrapbook'
    | '/_app/settings'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SetupRequiredRoute: typeof SetupRequiredRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup-required': {
      id: '/setup-required'
      path: '/setup-required'
      fullPath: '/setup-required'
      preLoaderRoute: typeof SetupRequiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scrapbook': {
      id: '/_app/scrapbook'
      path: '/scrapbook'
      fullPath: '/scrapbook'
      preLoaderRoute: typeof AppScrapbookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finances': {
      id: '/_app/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AppFinancesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brand-deals': {
      id: '/_app/brand-deals'
      path: '/brand-deals'
      fullPath: '/brand-deals'
      preLoaderRoute: typeof AppBrandDealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBrandDealsRoute: typeof AppBrandDealsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinancesRoute: typeof AppFinancesRoute
  AppScrapbookRoute: typeof AppScrapbookRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBrandDealsRoute: AppBrandDealsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinancesRoute: AppFinancesRoute,
  AppScrapbookRoute: AppScrapbookRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SetupRequiredRoute: SetupRequiredRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
